passing:
  passing_yds: 0.04
  passing_td: 4.0
  passing_two_pt: 2.0
  interceptions: -1.0

rushing:
  rushing_yds: 0.1
  rushing_td: 6.0
  rushing_two_pt: 2.0

receiving:
  receptions: 0.5
  receiving_yds: 0.1
  receiving_td: 6.0
  receiving_two_pt: 2.0

kicking:
  fg_0_19: 3.0
  fg_20_29: 3.0
  fg_30_39: 3.0
  fg_40_49: 4.0
  fg_50_plus: 5.0
  pat_made: 1.0
  pat_missed: -1.0
  fg_missed: -1.0
Defense:
  sacks: 1.0
  interceptions: 2.0
  fumble_recovery: 2.0
  defensive_td: 6.0
  safety: 2.0
  Forced Funbles: 1.0
  Blocked Kicks: 2.0
  points_allowed_0: 10.0
  points_allowed_1_6: 7.0
  points_allowed_7_13: 4.0
  points_allowed_14_20: 1.0
  points_allowed_21_27: 0
  points_allowed_28_34: -1.0
  points_allowed_35_plus: -4.0
fumbles:
  fumbles_lost: -2.0
  